import "../public/css/mapsjs-ui.css";
import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";

import HereMapScript from "@/app/components/scripts/HereMapScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <HereMapScript />
        </body>
      </html>
    </>
  );
}
